services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: m_blog_server
    ports:
      - "5432:5432"
    networks:
      - breeze-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data/
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app # Mount your local 'app' directory to '/app' in the container
    command: bun dev
    stdin_open: true
    tty: true # Keeps the container running for debugging
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.production
    networks:
      - breeze-network

volumes:
  db_data:

networks:
  breeze-network:
    driver: bridge
